export const metas = {
    "UNA|CATALAO": { switch: 2 },
    "UNA|KARAIBA": { switch: 2 },
    "UNA|BETIM": { switch: 2, nobreak: 1 },
    "UNA|BOMDESPACHO": { switch: 2 },
    "UNA|SETELAGOAS": { switch: 2 },
    "UNA|UBERLANDIA": { nobreak: 2 },
    "UNA|POUSOALEGRE": { switch: 2 },
    "AGES|SENHORDOBONFIM": { switch: 2, nobreak: 1 },
    "AGES|PARIPIRANGA": { switch: 1, nobreak: 1 },
    "AGES|JACOBINA": { switch: 1, nobreak: 1 },
    "AGES|IRECE": { nobreak: 1 },
    "FASEH|VESPASIANO": { switch: 2 },
    "UNIBH|ESTORIL": { switch: 10, nobreak: 10 },
    "UNIFG|GUANAMBI": { switch: 2, nobreak: 1 },
    "UNP|SALGADOFILHO": { switch: 10 },
    "UNP|MOSSORO": { switch: 2 },
    "UNIFACS|TANCREDONEVES": { switch: 3, nobreak: 5 },
    "FG|PIEDADE": { switch: 2, nobreak: 1 },
    "IBMR|BARRA": { switch: 2, nobreak: 1 },
    "UAM|MOOCA": { switch: 5, nobreak: 5 },
    "UAM|PAULISTA": { switch: 3, nobreak: 1 },
    "UAM|VILAOLIMPIA": { switch: 3 },
    "UNR|ZONASUL": { switch: 10, nobreak: 1 },
    "UNR|CANOAS": { switch: 4, nobreak: 1 },
    "UNISUL|TUBARAO": { switch: 5, nobreak: 2 },
    "UNISOCIESC|BLUMENAU": { switch: 5, nobreak: 1 },
    "UNISOCIESC|ANITAGARIBALDI": { switch: 2 },
    "HSM|LEARNINGVILLAGE": { switch: 4, nobreak: 1 },
  };